import '../globals.css';
import Header from '../_components/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='max-w-6xl mx-auto'>
        <Header />
        {children}
      </body>
    </html>
  );
}
